LOW_CONFIDENCE_THRESHOLD = 75.0
SIZE_ORDER = ('S', 'M', 'L', 'XL', 'XXL')
DEFAULT_SIZE_RATIO = {'S': 4, 'M': 7, 'L': 7, 'XL': 4, 'XXL': 4}

DRESS_ATTRIBUTES = {
    'dress_print': [
        'Abstract', 'Animal', 'AOP', 'Aztec', 'Bohemian', 'Camouflage',
        'Chain', 'Checked', 'Color Block', 'Conversational', 'Denim',
        'Ditsy Print', 'Embellished', 'Embroidered', 'Floral', 'Geometric',
        'Gingham checks', 'Graphic', 'Lace', 'Other', 'Paisley', 'Plain',
        'Polka Dot', 'Scarf', 'Self Design', 'Sequin', 'Slogan', 'Snake Print',
        'Spot', 'Stars & Moons', 'Striped', 'Tie and Dye', 'Tribal',
        'Tropical', 'Houndstooth', 'Foil', 'Logo',
    ],
    'dress_length': ['Maxi', 'Midi', 'Mini', 'Knee Length'],
    'dress_shape': [
        'A-Line', 'Blazer', 'Bodycon', 'Cape', 'Jumper', 'Pinafore',
        'Sheath', 'Shift', 'Shirt', 'Skater', 'Slip', 'Smock', 'Sweater',
        'Swing', 'Tea Dress', 'Tiered', 'T-Shirt', 'Tunic', 'Wiggle',
        'Wrap', 'Kaftan',
    ],
    'sleeve_length': [
        '3/4 Sleeves', 'Long Sleeves', 'One Sleeve', 'Short Sleeves',
        'Sleeveless', 'Strapless', 'Strappy',
    ],
    'neck_women': [
        'Asymmetric Neck', 'Bandeau Neck', 'Bardot Neck', 'Boat Neck',
        'Collared', 'Cowl Neck', 'Halter Neck', 'High Neck', 'Keyhole Neck',
        'Off Shoulder Neck', 'One Shoulder Neck', 'Polo Neck', 'Racer Neck',
        'Roll Neck', 'Round Neck', 'Scoop Neck', 'Square Neck',
        'Sweetheart Neck', 'Tie-Up Neck', 'Turtle Neck', 'V Neck',
        'Hooded', 'Notch Neck', 'Peter Pan', 'Wide Neck',
    ],
    'sleeve_styling': [
        'Angel Sleeve', 'Bell Sleeve', 'Cap Sleeve', 'Cape Sleeve',
        'Cold Shoulder Sleeve', 'Cuffed Sleeve', 'Kimono Sleeve', 'Puff Sleeve',
        'Raglan Sleeve', 'Regular Sleeve', 'Roll-Up Sleeve', 'Ruched Sleeve',
        'Slit Sleeve', 'No Sleeve', 'Bishop Sleeve', 'Ruffled', 'Batwing Sleeve',
        'Flute Sleeve', 'Balloon Sleeve', 'Tie Sleeve', 'Marie Sleeves',
        'One Sleeve', 'Frill Sleeve', 'Tulip Sleeve',
    ],
}

PO_EXPORT_GROUP_ROW = [
    'Core',
    'Core',
    'Core',
    'Core',
    'Core',
    'Core',
    'Core',
    'Core',
    'Core',
    'Core',
    'Core',
    'Core',
    'Core',
    'Core',
    'Tops',
    'Tops',
    'Tops',
    'Tops',
    'Tops',
    'Tops',
    'Trousers',
    'Trousers',
    'Dress',
    'Dress',
    'Dress',
    'Dress',
    'Dress',
    'Dress',
    'Coord Set / Jumpsuits',
    'Coord Set / Jumpsuits',
    'Coord Set / Jumpsuits',
    'Coord Set / Jumpsuits',
    'Coord Set / Jumpsuits',
    'Coord Set / Jumpsuits',
    'Ethnic Kurti / Set',
    'Ethnic Kurti / Set',
    'Ethnic Kurti / Set',
    'Ethnic Kurti / Set',
    'Ethnic Kurti / Set',
    'Ethnic Kurti / Set',
    'Ethnic Kurti / Set',
    'Denim Jeans',
    'Denim Jeans',
    'Denim Jeans',
    'Denim Jeans',
    'Outerwear / Jackets',
    'Outerwear / Jackets',
    'Outerwear / Jackets',
]

PO_EXPORT_HEADERS = [
    'Style Code',
    'Brand Name',
    'Category Type',
    'SKU Id',
    'Color',
    'Size',
    'L1',
    'Fibre Composition',
    'COO',
    'PO PRICE',
    'OSP in SAR',
    'PO Qnty',
    'Knitted / Wovan',
    'Product Name / Title',
    'Tops_Fit',
    'Top_Style',
    'Top_Neck',
    'Top_Length',
    'Top_pattern & Prints',
    'sleeve_length',
    '*pattern',
    '*product_type_trousers',
    'Dress Print',
    'Dress Length',
    'Dress Shape',
    '*sleeve_length_women_topwear_dr(dress)',
    '*neck_women(dress)',
    '*sleeve_styling(dress)',
    '*pattern',
    '*print_or_pattern_type',
    '*bottom_type_sets',
    '*top_type_set',
    'Print',
    'Length',
    'ethnic_sleeve_length',
    '*ethnic_pattern',
    '*ethnic_fit',
    '*ethnic_type',
    '*ethnic_neckline',
    '*ethnic_leg_style',
    'ethnic_sleeve_type',
    'Jeans_Fit',
    'Jeans_Waist Rise',
    'Jeans_stretch',
    'Jeans_Wash Shade',
    'pattern',
    'product_type_Outerwear',
    'length_topwear_nightwear_outer',
]
